# 服务器相关
server:
  port: 8082

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  application:
    name: user-client
eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
